// src/composables/extraModes.ts
// Définition de tous les modes additionnels au format tonal.js
import type { ModeGuitar } from '../types';

export const EXTRA_MODES: ModeGuitar[] = [
    // MODES PRINCIPAUX

    {
      name: "ionian",
      aliases: ["major", "M"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3M", "4P", "5P", "6M", "7M"],
      alt: [],
      triad: "major",
      seventh: "maj7",
      description: "Le mode ionien est la gamme majeure traditionnelle, caractérisé par sa sonorité lumineuse et équilibrée. Il exprime la joie, la stabilité et l'affirmation, formant la base de la musique occidentale classique et populaire. Sa structure d'intervalles crée une résolution harmonique naturelle qui procure un sentiment de complétude. Omniprésent dans les hymnes, chansons enfantines et compositions classiques, il est idéal pour transmettre des émotions positives et claires. Cette tonalité majeure constitue le point de référence pour tous les autres modes diatoniques.",
      culture: "Occidentale classique"
    },
    {
      name: "dorian",
      aliases: ["dor", "m"],
      modeNum: 1,
      mode: 1,
      intervals: ["1P", "2M", "3m", "4P", "5P", "6M", "7m"],
      alt: ["b3", "b7"],
      triad: "minor",
      seventh: "min7",
      description: "Le mode dorien, avec sa sixte majeure distinctive, crée un équilibre unique entre mélancolie et optimisme. Il exprime la contemplation, la nostalgie teintée d'espoir, et une profondeur émotionnelle sans tomber dans le dramatique. Prisé dans le jazz modal, le folk et la musique celtique, ce mode offre une palette expressive riche et nuancée. Sa sonorité reconnaissable traverse les époques, de la musique médiévale aux morceaux emblématiques comme 'So What' de Miles Davis. Le dorien constitue un outil puissant pour l'improvisation et la composition, évoquant une mélancolie qui n'est jamais désespérée.",
      culture: "Celtique & Jazz modal"
    },
    {
      name: "phrygian",
      aliases: ["phry"],
      modeNum: 2,
      mode: 2,
      intervals: ["1P", "2m", "3m", "4P", "5P", "6m", "7m"],
      alt: ["b2", "b3", "b6", "b7"],
      triad: "minor",
      seventh: "min7",
      description: "Le mode phrygien se distingue immédiatement par sa seconde mineure qui génère une tension caractéristique et une couleur orientale. Il évoque le mystère, l'intensité et parfois la menace, créant une atmosphère dramatique et exotique. Pilier du flamenco et de la musique andalouse, il imprègne de nombreuses compositions méditerranéennes et moyen-orientales. Sa structure crée une forte tension vers la tonique, produisant un sentiment d'urgence ou d'inévitabilité. Le phrygien est particulièrement efficace dans le metal, la musique électronique et les compositions cherchant à créer une ambiance sombre et énigmatique.",
      culture: "Espagnole & Moyen-orientale"
    },
    {
      name: "lydian",
      aliases: ["lyd", "maj#4"],
      modeNum: 3,
      mode: 3,
      intervals: ["1P", "2M", "3M", "4A", "5P", "6M", "7M"],
      alt: ["#4"],
      triad: "major",
      seventh: "maj7",
      description: "Le mode lydien, avec sa caractéristique quarte augmentée, crée une atmosphère aérienne, flottante et onirique. Il évoque l'émerveillement, le mystère et l'ouverture, transportant l'auditeur vers des territoires imaginaires et surréels. Fréquemment utilisé dans les musiques de films de science-fiction et fantasy, il colore les œuvres d'une qualité éthérée et transcendante. Le triton entre la tonique et la quarte lui confère cette sonorité distinctive qui semble défier la gravité. Favori des compositeurs impressionnistes comme Debussy et de jazzmen comme Bill Evans, le lydien invite à l'exploration harmonique et à l'élévation spirituelle.",
      culture: "Impressionnisme & Cinéma"
    },
    {
      name: "mixolydian",
      aliases: ["mixo", "dom"],
      modeNum: 4,
      mode: 4,
      intervals: ["1P", "2M", "3M", "4P", "5P", "6M", "7m"],
      alt: ["b7"],
      triad: "major",
      seventh: "7",
      description: "Le mode mixolydien, essentiellement une gamme majeure avec septième mineure, offre un équilibre parfait entre énergie majeure et tension subtile. Il exprime la vitalité, l'affirmation teintée de blues, et une joie qui n'est jamais complètement résolue. Omniprésent dans le rock, le blues et la musique celtique, il forme le fondement de nombreux riffs emblématiques comme ceux de 'Sweet Home Alabama'. Sa structure crée naturellement un mouvement vers le quatrième degré, expliquant sa présence dans d'innombrables progressions I-bVII-IV. Le mixolydien est l'outil idéal pour l'improvisation sur des accords dominants, offrant une transition naturelle entre les univers majeurs et mineurs.",
      culture: "Rock & Blues"
    },
    {
      name: "aeolian",
      aliases: ["minor", "m"],
      modeNum: 5,
      mode: 5,
      intervals: ["1P", "2M", "3m", "4P", "5P", "6m", "7m"],
      alt: ["b3", "b6", "b7"],
      triad: "minor",
      seventh: "min7",
      description: "Le mode éolien, ou gamme mineure naturelle, est fondamental pour exprimer la mélancolie, l'introspection et la profondeur émotionnelle. Il évoque la nostalgie, le drame intérieur et parfois la tristesse, avec une qualité inachevée qui invite à la contemplation. Omniprésent dans le répertoire romantique classique, le rock alternatif et les ballades émotionnelles, il permet d'explorer les émotions complexes et nuancées. Sa structure avec tierces, sixtes et septièmes mineures crée cette sonorité immédiatement reconnaissable qui touche les cordes sensibles de l'âme. L'éolien possède une versatilité émotionnelle allant de la douce mélancolie à la profonde tristesse, rendant compte de toute la palette des émotions sombres.",
      culture: "Classique romantique & Rock"
    },
    {
      name: "locrian",
      aliases: ["loc"],
      modeNum: 6,
      mode: 6,
      intervals: ["1P", "2m", "3m", "4P", "5d", "6m", "7m"],
      alt: ["b2", "b3", "b5", "b6", "b7"],
      triad: "diminished",
      seventh: "min7b5",
      description: "Le mode locrien, le plus dissonant des modes diatoniques, se distingue par sa quinte diminuée créant une instabilité permanente. Il évoque le chaos, l'angoisse et l'incertitude, générant une tension extrême qui cherche presque toujours à se résoudre. Rarement utilisé comme tonalité principale, il apparaît dans le metal progressif, le jazz expérimental et la musique contemporaine pour des moments de tension maximale. Son triton entre la tonique et la quinte lui confère cette qualité profondément instable et inquiétante. Des compositeurs comme Bartók et des groupes comme Dream Theater l'ont exploité pour créer des moments d'expressivité dramatique intense.",
      culture: "Metal progressif & Contemporain"
    },
    // MODES MINEURS MÉLODIQUES ET HARMONIQUES
    {
      name: "melodic minor",
      aliases: ["melodic", "jazz minor"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "4P", "5P", "6M", "7M"],
      alt: [],
      triad: "minor",
      seventh: "minMaj7",
      description: "Le mode mineur mélodique combine la chaleur mineure avec une tension ascendante créée par les sixte et septième majeures. Il évoque la sophistication, l'élégance et une mélancolie nuancée qui s'ouvre vers la résolution. Fondamental dans le jazz moderne et la musique classique, il offre un parfait équilibre entre profondeur émotionnelle et richesse harmonique. Sa sonorité distinctive a inspiré d'innombrables compositions de Bach à Bill Evans, permettant des progressions harmoniques complexes et des mélodies expressives. Le mineur mélodique représente l'alliance parfaite entre la tradition classique et l'innovation jazz.",
      culture: "Jazz moderne"
    },
    {
      name: "dorian b2",
      aliases: ["phrygian #6", "melodic minor second mode"],
      modeNum: 1,
      mode: 1,
      intervals: ["1P", "2m", "3m", "4P", "5P", "6M", "7m"],
      alt: ["b2"],
      triad: "minor",
      seventh: "min7",
      description: "Le mode dorien bémol 2 combine la mélancolie du dorien avec la tension dramatique d'une seconde mineure. Il évoque à la fois l'introspection du dorien et l'exotisme oriental du phrygien, formant un pont unique entre cultures musicales occidentales et orientales. Présent dans la musique juive klezmer, indienne et modale contemporaine, il apporte une tension expressive unique. Sa dualité entre la seconde mineure sombre et la sixte majeure lumineuse crée un équilibre émotionnel complexe. Le dorien bémol 2 (ou phrygien dièse 6) illustre parfaitement comment une simple altération peut transformer radicalement le caractère expressif d'un mode.",
      culture: "Klezmer & Contemporain"
    },
    {
      name: "lydian augmented",
      aliases: ["lydian #5", "melodic minor third mode"],
      modeNum: 2,
      mode: 2,
      intervals: ["1P", "2M", "3M", "4A", "5A", "6M", "7M"],
      alt: ["#4", "#5"],
      triad: "augmented",
      seventh: "maj7#5",
      description: "Le mode lydien augmenté, avec sa quarte augmentée et sa quinte augmentée, pousse l'étrangeté du lydien encore plus loin dans le territoire de l'altération et du surréalisme. Il évoque le mystère, la transcendance et une luminosité presque surnaturelle grâce à ses deux altérations ascendantes. Particulièrement prisé dans le jazz moderne, la musique de film d'anticipation et les compositions expérimentales, il crée des couleurs harmoniques particulièrement riches. Sa structure intervallique unique génère une forte tension qui semble défier la gravité tonale traditionnelle. Le lydien augmenté représente l'une des expressions les plus avancées de la modernité harmonique tout en maintenant une certaine accessibilité émotionnelle.",
      culture: "Jazz d'avant-garde"
    },
    {
      name: "lydian dominant",
      aliases: ["mixolydian #11", "melodic minor fourth mode"],
      modeNum: 3,
      mode: 3,
      intervals: ["1P", "2M", "3M", "4A", "5P", "6M", "7m"],
      alt: ["#4", "b7"],
      triad: "major",
      seventh: "7#11",
      description: "Le mode lydien dominant fusionne la brillance éthérée du lydien avec l'énergie terrienne du mixolydien. Il associe l'élévation spirituelle de la quarte augmentée à la tension bluesy de la septième mineure, créant un équilibre parfait entre sophistication et accessibilité. Pilier du jazz fusion et des compositions de musiciens comme Joe Satriani ou John Scofield, il offre une richesse harmonique particulièrement adaptée aux solos expressifs. Sa dualité entre tension et résolution, entre modernité et tradition, explique sa popularité dans les compositions contemporaines. Le lydien dominant incarne l'évolution naturelle du langage harmonique du jazz, combinant influence africaine-américaine et sophistication européenne.",
      culture: "Jazz fusion"
    },
    {
      name: "melodic major",
      aliases: ["mixolydian b6", "melodic minor fifth mode"],
      modeNum: 4,
      mode: 4,
      intervals: ["1P", "2M", "3M", "4P", "5P", "6m", "7m"],
      alt: ["b6", "b7"],
      triad: "major",
      seventh: "7",
      description: "Le mode majeur mélodique (ou mixolydien bémol 6) combine la luminosité majeure avec une tension mélancolique créée par sa sixte mineure. Il crée un pont entre la joie du majeur et la profondeur émotionnelle du mineur, offrant une expressivité particulièrement riche et nuancée. Présent dans de nombreuses musiques ethniques, notamment des Balkans, et repris par des compositeurs comme Bartók, il apporte une couleur modale distinctive. Sa combinaison de tierce majeure et sixte mineure évoque une nostalgie lumineuse plutôt qu'une tristesse profonde. Le majeur mélodique représente parfaitement l'expression de sentiments complexes et paradoxaux, incarnant la dualité émotionnelle inhérente à l'expérience humaine.",
      culture: "Balkanique & Est-européenne"
    },
    {
      name: "half diminished",
      aliases: ["locrian #2", "melodic minor sixth mode"],
      modeNum: 5,
      mode: 5,
      intervals: ["1P", "2M", "3m", "4P", "5d", "6m", "7m"],
      alt: ["b5", "b6", "b7"],
      triad: "diminished",
      seventh: "min7b5",
      description: "Le mode demi-diminué (ou locrien dièse 2) adoucit légèrement la tension extrême du locrien tout en maintenant son caractère profondément instable. Il évoque l'incertitude, la transition et une anxiété contenue, rendant sa résolution encore plus satisfaisante. Fondamental dans le jazz pour les accords de passage II-V-I en mineur, il constitue un vocabulaire harmonique essentiel des progressions d'accords sophistiquées. Sa seconde majeure offre un point d'appui mélodique tout en préservant la tension dramatique de la quinte diminuée. Le demi-diminué représente l'équilibre parfait entre tension et fonction harmonique claire, expliquant son omniprésence dans les compositions jazz de Duke Ellington à John Coltrane.",
      culture: "Jazz modal"
    },
    {
      name: "altered",
      aliases: ["super locrian", "melodic minor seventh mode"],
      modeNum: 6,
      mode: 6,
      intervals: ["1P", "2m", "3m", "4d", "5d", "6m", "7m"],
      alt: ["b2", "b3", "b4", "b5", "b6", "b7"],
      triad: "diminished",
      seventh: "7alt",
      description: "Le mode altéré, avec ses multiples altérations descendantes, représente le paroxysme de la tension harmonique dans le langage jazz. Il évoque le chaos contrôlé, la dissonance expressive et l'urgence de résolution, créant une intensité dramatique inégalée. Utilisé exclusivement sur les dominantes altérées dans le jazz moderne et contemporain, il offre un maximum de possibilités chromatiques pour l'improvisation avancée. Sa structure intervallique unique, avec quarte et quinte diminuées, génère cette instabilité extrême qui annonce et valorise la résolution. Le mode altéré incarne l'évolution ultime du langage bebop, poussant la tension harmonique à ses limites tout en maintenant la cohérence fonctionnelle.",
      culture: "Jazz contemporain"
    },
    {
      name: "harmonic minor",
      aliases: ["minor harmonic"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "4P", "5P", "6m", "7M"],
      alt: ["b3", "b6"],
      triad: "minor",
      seventh: "minMaj7",
      description: "Le mode mineur harmonique, avec son intervalle augmenté caractéristique entre le sixième et septième degré, évoque immédiatement mystère et exotisme. Il combine la profondeur émotionnelle du mineur avec une tension dramatique créée par sa septième majeure. Utilisé abondamment dans la musique classique, le flamenco et la musique tzigane, il apporte une intensité dramatique sans pareille. Sa sonorité distinctive a inspiré d'innombrables compositeurs, de Mozart à Rimsky-Korsakov, pour représenter des atmosphères orientales ou magiques. Le mineur harmonique transcende les frontières culturelles pour exprimer passion et mystère avec une couleur harmonique immédiatement reconnaissable.",
      culture: "Classique & Tzigane"
    },
    {
      name: "locrian 6",
      aliases: ["harmonic minor second mode"],
      modeNum: 1,
      mode: 1,
      intervals: ["1P", "2m", "3m", "4P", "5d", "6M", "7m"],
      alt: ["b2", "b3", "b5", "b7"],
      triad: "diminished",
      seventh: "min7b5",
      description: "Le mode locrien 6, avec sa sixte majeure contrastant avec la quinte diminuée, crée une tension harmonique unique et paradoxale. Il évoque une instabilité sophistiquée, une mélancolie complexe et une tension qui cherche résolution sans être totalement désespérée. Rarement utilisé comme tonalité principale, il apparaît dans le jazz contemporain et la musique classique moderne pour des moments de tension dramatique. Sa structure particulière offre un équilibre fascinant entre dissonance extrême et lueur d'espoir apportée par la sixte majeure. Le locrien 6 représente la capacité de la musique moderne à exprimer des émotions complexes et contradictoires, reflétant la dualité de l'expérience humaine.",
      culture: "Jazz d'avant-garde"
    },
    {
      name: "ionian #5",
      aliases: ["harmonic minor third mode"],
      modeNum: 2,
      mode: 2,
      intervals: ["1P", "2M", "3M", "4P", "5A", "6M", "7m"],
      alt: ["#5", "b7"],
      triad: "augmented",
      seventh: "aug7",
      description: "Le mode ionien dièse 5 transforme la stabilité du mode majeur en une sonorité plus tendue et exotique grâce à sa quinte augmentée. Il évoque à la fois la familiarité du majeur et l'étrangeté d'une harmonie augmentée, créant une brillance teintée de mystère et d'anticipation. Utilisé principalement dans le jazz moderne et les musiques de film, il colore les compositions d'une tension subtile et sophistiquée. Sa capacité à fusionner consonance et dissonance en fait un outil expressif particulièrement riche pour les compositeurs contemporains. L'ionien dièse 5 illustre parfaitement comment une simple altération peut transformer radicalement le caractère émotionnel et expressif d'un mode familier.",
      culture: "Jazz moderne"
    },
    {
      name: "dorian #4",
      aliases: ["harmonic minor fourth mode"],
      modeNum: 3,
      mode: 3,
      intervals: ["1P", "2M", "3m", "4A", "5P", "6M", "7m"],
      alt: ["b3", "#4", "b7"],
      triad: "minor",
      seventh: "min7",
      description: "Le mode dorien dièse 4 enrichit la mélancolie équilibrée du dorien avec la tension spectrale de la quarte augmentée. Il évoque une introspection teintée d'étrangeté, une mélancolie aux couleurs surréalistes, créant cette dualité entre familiarité et altérité. Utilisé dans la musique contemporaine, le jazz expérimental et certaines musiques ethniques d'Europe de l'Est, il offre une palette expressive unique. Sa combinaison de mélancolie mineure et de tension lydienne crée un équilibre fascinant entre émotion et intellect. Le dorien dièse 4 représente l'évolution naturelle du langage modal, transcendant les catégories traditionnelles pour exprimer des émotions complexes propres à la sensibilité contemporaine.",
      culture: "Contemporain & Est-européen"
    },
    {
      name: "phrygian dominant",
      aliases: ["spanish phrygian", "harmonic minor fifth mode"],
      modeNum: 4,
      mode: 4,
      intervals: ["1P", "2m", "3M", "4P", "5P", "6m", "7m"],
      alt: ["b2", "b6", "b7"],
      triad: "major",
      seventh: "7",
      description: "Le mode phrygien dominant, avec son mélange unique de tierce majeure et seconde mineure, incarne l'essence de la musique espagnole et méditerranéenne. Il évoque immédiatement passion, intensité et chaleur, créant cette tension caractéristique du flamenco et de la musique andalouse. Sa structure intervallique particulière crée un effet de balancement entre exotisme oriental et familiarité occidentale. Pilier du flamenco, de la musique séfarade et des musiques du Moyen-Orient, ce mode transcende les frontières géographiques et culturelles. Le phrygien dominant possède cette remarquable capacité à évoquer instantanément un paysage sonore méditerranéen, même dans les oreilles non initiées.",
      culture: "Espagnole & Méditerranéenne"
    },
    {
      name: "lydian #2",
      aliases: ["harmonic minor sixth mode"],
      modeNum: 5,
      mode: 5,
      intervals: ["1P", "2A", "3M", "4A", "5P", "6M", "7M"],
      alt: ["#2", "#4"],
      triad: "major",
      seventh: "maj7",
      description: "Le mode lydien dièse 2, avec sa seconde augmentée distinctive, pousse l'étrangeté du lydien encore plus loin dans le territoire de l'altération et de l'exotisme. Il évoque des sonorités orientales et mystiques tout en conservant la brillance aérienne caractéristique du lydien. Utilisé dans les compositions modernes, le jazz d'avant-garde et certaines musiques de film, il crée une atmosphère à la fois tendue et transcendante. Sa combinaison unique d'intervalles augmentés génère cette impression de suspension gravitationnelle et d'altérité. Le lydien dièse 2 représente l'une des expressions les plus avancées de la fusion entre influences orientales et occidentales dans le langage musical contemporain.",
      culture: "Fusion orientale & Contemporain"
    },
    {
      name: "ultralocrian",
      aliases: ["super locrian bb7", "harmonic minor seventh mode"],
      modeNum: 6,
      mode: 6,
      intervals: ["1P", "2m", "3m", "4d", "5d", "6m", "7d"],
      alt: ["b2", "b3", "b4", "b5", "b6", "bb7"],
      triad: "diminished",
      seventh: "dim7",
      description: "Le mode ultralocrien, avec sa septième doublement bémolisée, représente l'extrême limite de la dissonance et de l'instabilité harmonique. Il évoque le chaos absolu, la désintégration tonale et une tension qui semble impossible à résoudre par les moyens traditionnels. Rarement utilisé comme tonalité principale, il apparaît dans la musique contemporaine expérimentale et certaines expressions avant-gardistes du jazz. Sa structure intervallique unique, accumulant les altérations descendantes, pousse l'auditeur vers un territoire harmonique inexploré. L'ultralocrien incarne la recherche permanente de nouvelles frontières expressives en musique, questionnant les limites mêmes de notre perception tonale.",
      culture: "Avant-garde & Expérimental"
    },
    {
      name: "harmonic major",
      aliases: ["major harmonic"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3M", "4P", "5P", "6m", "7M"],
      alt: ["b6"],
      triad: "major",
      seventh: "maj7",
      description: "Le mode majeur harmonique, fusion du majeur ionien avec la sixte mineure distinctive, crée un pont fascinant entre la joie majeure et la mélancolie mineure. Il évoque une luminosité teintée de nostalgie, une joie contemplative plutôt qu'exubérante, donnant cette profondeur émotionnelle particulière. Utilisé par des compositeurs comme Chopin et Tchaïkovski, ainsi que dans certaines musiques traditionnelles d'Europe de l'Est, il enrichit le vocabulaire harmonique des compositions romantiques. Sa sixte mineure crée cette tension expressive qui résiste à la simplicité émotionnelle du majeur pur. Le majeur harmonique illustre parfaitement la sophistication émotionnelle que peut apporter une simple altération stratégique dans un mode familier.",
      culture: "Romantique européen"
    },
  
    // GAMMES PENTATONIQUES
    {
      name: "major pentatonic",
      aliases: ["pentatonic"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3M", "5P", "6M"],
      alt: [],
      triad: "major",
      seventh: "6",
      description: "La gamme pentatonique majeure, avec ses cinq notes harmonieusement arrangées, offre une sonorité universellement agréable et intuitive. Elle exprime la joie, la simplicité et une clarté qui transcende les cultures musicales du monde entier. Sans demi-tons, elle crée une consonance naturelle qui évite les tensions, la rendant parfaite pour l'improvisation et les mélodies mémorables. Fondamentale dans la musique folk, country, pop et rock, cette gamme représente le langage musical le plus accessible et immédiat. Des chansons enfantines traditionnelles aux solos de guitare classiques, la pentatonique majeure incarne l'essence même de la communication musicale directe et universelle.",
      culture: "Musiques traditionnelles mondiales"
    },
    {
      name: "minor pentatonic",
      aliases: ["minor pent"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "3m", "4P", "5P", "7m"],
      alt: ["b3", "b7"],
      triad: "minor",
      seventh: "min7",
      description: "La gamme pentatonique mineure, pierre angulaire du blues et du rock, possède une expressivité émotionnelle incomparable malgré sa simplicité. Elle évoque à la fois mélancolie et force, introspection et rébellion, avec une tension subtile qui ne verse jamais dans la dissonance. Sans demi-tons, elle offre une liberté d'improvisation qui pardonne les erreurs tout en permettant une profonde expression personnelle. Des pleurs de la guitare blues aux riffs puissants du hard rock, cette gamme a façonné l'histoire de la musique populaire moderne. La pentatonique mineure représente le parfait équilibre entre accessibilité technique et profondeur émotionnelle, expliquant son omniprésence dans pratiquement tous les genres musicaux contemporains.",
      culture: "Blues & Rock"
    },
    {
      name: "ritusen",
      aliases: ["major pentatonic b2"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "4P", "5P", "6M"],
      alt: ["b2"],
      triad: "sus4",
      seventh: "sus4add6",
      description: "La gamme ritusen, variante japonaise de la pentatonique avec sa seconde mineure caractéristique, évoque immédiatement l'atmosphère contemplative et méditative de la musique traditionnelle d'Extrême-Orient. Elle exprime sérénité, espace et une forme de transcendance qui invite à la contemplation plutôt qu'à l'action. Utilisée principalement dans la musique japonaise et certaines compositions contemporaines d'inspiration orientale, elle crée ce paysage sonore immédiatement reconnaissable. Son absence de tierce génère cette qualité flottante, suspendue entre majeur et mineur. La ritusen représente parfaitement la philosophie esthétique japonaise du ma - l'espace entre les choses - où le silence et la retenue sont aussi importants que les notes jouées.",
      culture: "Japonaise"
    },
    {
      name: "man gong",
      aliases: ["major pentatonic b6"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "4P", "5P", "6m"],
      alt: ["b6"],
      triad: "sus4",
      seventh: "7sus4",
      description: "La gamme man gong, avec son mélange de quarte juste et sixte mineure, crée une sonorité ouverte et contemplative évoquant les paysages sonores traditionnels d'Extrême-Orient. Elle exprime une tranquillité teintée de mélancolie, une sérénité qui accepte la dualité de l'existence. Utilisée dans les musiques traditionnelles chinoises et certaines compositions contemporaines d'inspiration orientale, elle transcende la division occidentale majeur/mineur. Son absence de tierce lui confère cette qualité neutre et méditative caractéristique de la philosophie musicale orientale. Le man gong représente l'équilibre parfait entre espace et émotion, incarnant l'idéal esthétique oriental où la suggestion est préférée à l'affirmation directe.",
      culture: "Chinoise"
    },
    {
      name: "yo",
      aliases: ["pentatonic b3 b7"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "5P", "7m"],
      alt: ["b3", "b7"],
      triad: "minor",
      seventh: "min7",
      description: "La gamme yo, fondamentale dans la musique traditionnelle japonaise, crée un pont fascinant entre les sensibilités orientales et occidentales avec sa structure pentatonique mineure. Elle évoque une mélancolie paisible, une acceptation sereine de l'impermanence, incarnant parfaitement le concept esthétique japonais du mono no aware. Utilisée principalement sur des instruments comme le shakuhachi et le koto, elle communique cette contemplation tranquille si caractéristique de l'art japonais. Sa structure sans quarte ni sixte génère cet espace sonore ouvert où l'auditeur peut projeter ses propres émotions. La gamme yo représente l'équilibre parfait entre expression émotionnelle et retenue méditative, entre mélancolie et acceptation.",
      culture: "Japonaise"
    },
    {
      name: "blues minor",
      aliases: ["pentatonic b3 b5"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "3m", "4P", "5d", "7m"],
      alt: ["b3", "b5", "b7"],
      triad: "diminished",
      seventh: "min7b5",
      description: "La gamme blues mineure, avec sa quinte diminuée caractéristique, intensifie l'expressivité émotionnelle de la pentatonique mineure traditionnelle. Elle évoque une profonde tristesse, une plainte viscérale et cette tension bluesy qui semble exprimer la douleur humaine dans sa forme la plus pure. Parfaite pour le blues expressif, le jazz modal et certaines formes de rock alternatif, elle apporte une intensité dramatique incomparable aux solos et improvisations. Sa quinte diminuée, véritable blue note, crée cette instabilité expressive qui transcende les limites de la notation traditionnelle. La blues mineure incarne l'essence même de l'expression émotionnelle directe en musique, donnant voix aux plus profondes souffrances de l'âme humaine.",
      culture: "Blues expressif"
    },
    {
      name: "blues major",
      aliases: ["pentatonic b2 b5"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3M", "5d", "6M"],
      alt: ["b2", "b5"],
      triad: "augmented",
      seventh: "6",
      description: "La gamme blues majeure, fusionnant caractéristiques majeures et altérations blues, crée une sonorité à la fois lumineuse et tendue qui transcende la division traditionnelle majeur/mineur. Elle évoque la joie teintée de mélancolie, l'optimisme qui reconnaît la douleur, incarnant parfaitement la dualité émotionnelle du blues. Utilisée par des guitaristes comme Robben Ford et Larry Carlton, elle colore les improvisations jazz-blues d'une expressivité unique. Sa combinaison de tierce majeure et notes altérées génère cette tension expressive caractéristique. La blues majeure représente l'équilibre parfait entre tradition et innovation dans le vocabulaire bluesy, offrant aux musiciens un outil expressif capable de communiquer toute la complexité émotionnelle de l'expérience humaine.",
      culture: "Jazz-blues"
    },
  
    // GAMMES HEXATONIQUES
    {
      name: "whole tone",
      aliases: ["wholetone", "augmented"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3M", "4A", "5A", "7m"],
      alt: ["#4", "#5", "b7"],
      triad: "augmented",
      seventh: "7#5",
      description: "La gamme par tons entiers, parfaitement symétrique et dépourvue de centre tonal apparent, crée une atmosphère flottante et onirique qui transcende la tonalité traditionnelle. Elle évoque le mystère, l'apesanteur et une certaine instabilité qui semblent suspendre le temps musical. Popularisée par Debussy et les compositeurs impressionnistes, elle est devenue la signature sonore du rêve, de l'incertitude et de l'imaginaire dans la musique de film. Son absence de demi-tons et sa structure où chaque note est à égale distance génèrent cette qualité éthérée distinctive. La gamme par tons représente parfaitement l'ambiguïté et la fluidité, créant des paysages sonores où la résolution traditionnelle est délibérément évitée.",
      culture: "Impressionnisme français",
    },
    {
      name: "augmented triad",
      aliases: ["major augmented triad"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "3M", "5A"],
      alt: ["#5"],
      triad: "augmented",
      seventh: "maj7#5",
      description: "L'arpège augmenté, divisant l'octave en trois tierces majeures parfaitement égales, crée une symétrie harmonique qui défie la résolution tonale traditionnelle. Il évoque une tension mystique, une brillance surnaturelle et cette qualité suspendue qui semble transcender l'espace et le temps. Utilisé par des compositeurs comme Liszt, Debussy et des jazzmen comme John Coltrane dans sa période expérimentale, il colore les compositions d'une aura d'étrangeté sophistiquée. Sa structure symétrique parfaite génère cette ambiguïté fonctionnelle où chaque note peut potentiellement servir de fondamentale. L'arpège augmenté représente l'une des premières explorations de systèmes harmoniques non-occidentaux dans la musique européenne, annonçant l'exploration du total chromatique au 20e siècle.",
      culture: "Impressionnisme & Contemporain",
    },
    {
      name: "prometheus",
      aliases: ["prometheus scale", "lydian flat 7"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3M", "4A", "6M", "7m"],
      alt: ["#4", "b7"],
      triad: "lydian",
      seventh: "7#11",
      description: "La gamme prométhéenne, avec sa combinaison unique de quarte augmentée et septième mineure, évoque une tension cosmique, une brillance divine teintée d'humanité terrestre. Elle exprime l'élévation spirituelle et la transcendance tout en reconnaissant les limites de la condition humaine. Utilisée par Scriabine dans ses compositions mystiques et reprise par des musiciens de jazz comme Wayne Shorter, elle incarne parfaitement la quête spirituelle à travers l'art. Sa structure hexatonique particulière crée cette qualité à la fois lumineuse et tendue, entre ascension et ancrage terrestre. La gamme prométhéenne, comme son nom mythologique le suggère, représente la recherche humaine de connaissance divine et de transcendance, capturant musicalement cette aspiration vers la lumière.",
      culture: "Mystique russe",
    },
    {
      name: "blues",
      aliases: ["blues scale"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "3m", "4P", "5d", "5P", "7m"],
      alt: ["b3", "b5", "b7"],
      triad: "minor",
      seventh: "min7",
      description: "La gamme blues, avec sa caractéristique 'blue note' (quinte diminuée), capture l'essence même de l'expression émotionnelle dans la musique populaire américaine. Elle évoque à la fois la souffrance et la transcendance, la plainte et la catharsis, créant cette tension caractéristique qui fait l'âme du blues. Ce mélange unique de notes pentatoniques et de quinte diminuée permet ces inflexions vocales et instrumentales exprimant la douleur humaine et la résilience. Fondement du blues, du rock, du jazz et de presque toute la musique populaire moderne, cette gamme transcende ses origines afro-américaines pour devenir un langage universel d'expression émotionnelle. La gamme blues représente le parfait équilibre entre tradition folk et innovation, entre simplicité mélodique et complexité expressive.",
      culture: "Afro-américaine",
    },
  
    // GAMMES OCTATONIQUES ET SYMÉTRIQUES
    {
      name: "diminished",
      aliases: ["whole-half diminished", "octatonic"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "4P", "5d", "6m", "6M", "7M"],
      alt: ["b5"],
      triad: "diminished",
      seventh: "dim7",
      description: "La gamme diminuée ton-demi-ton, parfaitement symétrique dans sa construction alternée, crée une tension harmonique unique qui défie la résolution tonale traditionnelle. Elle évoque mystère, anxiété et cette qualité cyclique où la tension semble perpétuellement se renouveler sans jamais trouver sa résolution finale. Exploitée par des compositeurs comme Stravinsky, Bartók et de nombreux jazzmen, elle transcende les limites de la tonalité occidentale classique. Sa structure symétrique génère ces possibilités harmoniques fascinantes où les mêmes formes d'accords peuvent se déplacer par tierces mineures. La gamme diminuée représente une des premières explorations systématiques de l'organisation non-tonale du matériau sonore, annonçant les développements ultérieurs de la musique du 20e siècle.",
      culture: "Jazz & Contemporain",
    },
    {
      name: "half-whole diminished",
      aliases: ["half-whole", "octatonic"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3m", "3M", "5d", "5P", "6M", "7m"],
      alt: ["b2", "b3", "#3", "b5"],
      triad: "diminished",
      seventh: "dim7",
      description: "La gamme diminuée demi-ton-ton, version alternative de l'octatonique, intensifie encore la tension harmonique par sa seconde mineure initiale. Elle évoque une anxiété plus immédiate, un malaise plus prononcé, tout en conservant la fascinante symétrie qui caractérise les échelles octatoniques. Utilisée par des compositeurs comme Messiaen et dans le jazz moderne pour des improvisations sur accords altérés, elle offre un riche vocabulaire pour l'expression contemporaine. Sa structure symétrique permet ces modulations par tierces majeures qui créent des effets de kaléidoscope sonore. La gamme diminuée demi-ton-ton représente l'une des organisations les plus sophistiquées du matériau sonore dans la musique moderne, offrant un équilibre parfait entre contrainte structurelle et liberté expressive.",
      culture: "Contemporain & Jazz moderne",
    },
  
    // MODES JAPONAIS
    {
      name: "hirajoshi",
      aliases: ["japanese"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "5P", "6m"],
      alt: ["b3", "b6"],
      triad: "minor",
      seventh: "min7",
      description: "La gamme hirajoshi, pilier de la musique traditionnelle japonaise, crée instantanément cette atmosphère orientale reconnaissable par son exotisme méditatif. Elle évoque le calme, la contemplation et une certaine mélancolie élégante propre à l'esthétique japonaise. Utilisée principalement sur le koto et le shamisen, elle transpose l'auditeur dans un paysage sonore évoquant les jardins zen et la philosophie du wabi-sabi. Sa structure pentatonique particulière, avec ses secondes majeures et secondes augmentées caractéristiques, génère cette tension délicate et raffinée. L'hirajoshi représente l'équilibre parfait entre simplicité apparente et profondeur expressive, reflétant les valeurs esthétiques traditionnelles japonaises de suggestion plutôt que d'affirmation directe.",
      culture: "Japonaise",
    },
    {
      name: "in sen",
      aliases: ["japanese in"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "4P", "5P", "7m"],
      alt: ["b2", "b7"],
      triad: "sus4",
      seventh: "sus4",
      description: "La gamme in sen, avec sa seconde mineure initiale distinctive, crée immédiatement cette atmosphère mélancolique et contemplative caractéristique de certaines traditions musicales japonaises. Elle évoque mystère, intériorité et cette qualité méditative qui invite à la réflexion profonde plutôt qu'à l'expression extérieure. Utilisée principalement sur des instruments comme le shakuhachi, elle communique parfaitement l'esthétique du yugen - cette beauté profonde et mystérieuse des choses. Son absence de tierce génère cette ambiguïté émotionnelle caractéristique de la philosophie zen. L'in sen représente l'équilibre parfait entre expression émotionnelle et retenue méditative, incarnant l'idéal esthétique japonais où le silence et l'espace sont aussi importants que les sons articulés.",
      culture: "Japonaise",
    },
    {
      name: "iwato",
      aliases: ["japanese iwato"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "4P", "5d", "7m"],
      alt: ["b2", "b5", "b7"],
      triad: "diminished",
      seventh: "dim7",
      description: "La gamme iwato, avec sa combinaison unique de seconde mineure et quinte diminuée, crée une tension distinctive caractéristique de certaines traditions musicales japonaises anciennes. Elle évoque mystère, déséquilibre et cette qualité surnaturelle qui semble transcender la réalité ordinaire. Utilisée principalement dans le théâtre nô et certaines pièces pour shakuhachi, elle communique parfaitement le concept de yurei - l'atmosphère fantomatique et inquiétante. Sa structure particulièrement tendue génère cette ambiance dramatique souvent associée au mystique et au spirituel. L'iwato représente l'expression parfaite du concept japonais de ma - l'espace négatif chargé de tension et de signification - traduisant musicalement cette esthétique où ce qui n'est pas dit importe autant que ce qui est exprimé.",
      culture: "Japonaise traditionnelle",
    },
    {
      name: "kumoi",
      aliases: ["japanese kumoi"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "5P", "6M"],
      alt: ["b3"],
      triad: "minor",
      seventh: "min6",
      description: "La gamme kumoi, avec son mélange équilibré de tierce mineure et sixte majeure, crée un pont fascinant entre mélancolie et luminosité dans la tradition musicale japonaise. Elle évoque contemplation, sérénité et cette dualité émotionnelle qui caractérise la philosophie esthétique japonaise. Utilisée sur le koto et d'autres instruments traditionnels, elle exprime parfaitement le concept de mono no aware - la douce mélancolie de l'impermanence. Sa structure pentatonique particulière génère cette tension subtile qui n'est ni complètement triste ni totalement joyeuse. La kumoi représente l'équilibre parfait entre expression émotionnelle et retenue méditative, incarnant l'idéal esthétique japonais où la beauté est inséparable de l'éphémère.",
      culture: "Japonaise",
    },
  
    // GAMMES ETHNIQUES ET FOLKLORIQUES
    {
      name: "arabian",
      aliases: ["arabic", "hijaz"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3M", "4P", "5P", "6m", "7M"],
      alt: ["b2", "b6"],
      triad: "major",
      seventh: "maj7",
      description: "Le maqam hijaz (ou mode arabe), avec son intervalle caractéristique d'un ton et demi entre la seconde mineure et la tierce majeure, incarne l'essence même de la musique du Moyen-Orient. Il évoque immédiatement déserts, minarets et cette tension émotionnelle profonde qui caractérise l'expressivité orientale. Fondamental dans la musique arabe, turque et séfarade, il transcende les frontières géographiques et culturelles du monde méditerranéen. Sa seconde augmentée distinctive crée cette tension qui semble traduire musicalement la chaleur intense du désert et la passion de ses habitants. Le hijaz représente le parfait équilibre entre tradition millénaire et expressivité directe, servant de pont musical entre Orient et Occident depuis des siècles.",
      culture: "Arabe & Moyen-orientale",
    },
    {
      name: "persian",
      aliases: ["middle eastern"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3M", "4P", "5d", "6m", "7M"],
      alt: ["b2", "b5", "b6"],
      triad: "augmented",
      seventh: "maj7b5",
      description: "Le mode persan, avec ses multiples intervalles augmentés, capture l'essence même de la musique classique iranienne et ses ornementations sophistiquées. Il évoque les jardins suspendus de Babylone, l'opulence des poèmes de Rumi, et cette tension émotionnelle extatique caractéristique de la tradition soufie. Fondamental dans la musique savante persane jouée sur des instruments comme le tar ou le santur, il exprime la profondeur mystique et philosophique de cette culture millénaire. Ses intervalles inhabituels créent ces microtonalités et modulations expressives qui caractérisent le radif persan. Le mode persan représente l'une des traditions musicales les plus anciennes et sophistiquées du monde, équilibrant parfaitement structure mathématique rigoureuse et liberté expressive débridée.",
      culture: "Persane",
    },
    {
      name: "byzantine",
      aliases: ["double harmonic", "gypsy major"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3M", "4P", "5P", "6m", "7M"],
      alt: ["b2", "b6"],
      triad: "major",
      seventh: "maj7",
      description: "La gamme byzantine, avec ses deux secondes augmentées caractéristiques, incarne le mystère et l'exotisme de la musique orientale et méditerranéenne. Elle évoque immédiatement les bazars animés, les déserts infinis et la spiritualité mystique du Moyen-Orient. Sa structure inhabituelle, combinant éléments des gammes mineures harmoniques et phrygiennes dominantes, crée cette tension dramatique si reconnaissable. Fondamentale dans la musique grecque, turque, arabe et tzigane, elle a influencé d'innombrables compositeurs classiques cherchant à évoquer l'Orient. La gamme byzantine transcende les frontières géographiques pour créer un pont sonore entre l'Est et l'Ouest, incarnant parfaitement la fascination occidentale pour les sonorités orientales tout en respectant leurs traditions authentiques.",
      culture: "Grecque & Moyen-orientale",
    },
    {
      name: "hungarian minor",
      aliases: ["gypsy minor", "double harmonic minor"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "4A", "5P", "6m", "7M"],
      alt: ["#4", "b6"],
      triad: "minor",
      seventh: "minMaj7",
      description: "Le mode mineur hongrois, avec sa quarte augmentée et septième majeure caractéristiques, capture l'âme même de la musique tzigane d'Europe centrale. Il évoque passion, mélancolie profonde et cette virtuosité flamboyante si typique des violonistes roms. Sa structure unique, fusionnant éléments du mineur harmonique et du lydien, crée cette tension dramatique intense qui semble traduire l'histoire mouvementée des peuples nomades. Fondamental dans la musique tzigane hongroise, roumaine et des Balkans, il a influencé des compositeurs comme Liszt, Brahms et Bartók. Le mineur hongrois représente l'équilibre parfait entre tradition folklorique authentique et sophistication harmonique, incarnant l'intensité émotionnelle sans limite qui caractérise l'âme tzigane.",
      culture: "Tzigane & Hongroise",
    },
    {
      name: "hungarian major",
      aliases: ["gypsy major scale"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2A", "3M", "4A", "5P", "6M", "7m"],
      alt: ["#2", "#4", "b7"],
      triad: "augmented",
      seventh: "7#11",
      description: "Le mode majeur hongrois, avec ses multiples intervalles augmentés, représente l'apogée de l'exotisme dans la musique d'Europe centrale. Il évoque simultanément joie débridée et mélancolie poignante, virtuosité éblouissante et profondeur émotionnelle, caractéristiques de l'expression musicale tzigane. Sa structure unique, avec seconde et quarte augmentées, crée cette tension harmonique intense qui semble traduire l'esprit libre et indomptable des peuples roms. Intégré par Bartók et Kodály dans leurs compositions après leurs recherches ethnomusicologiques, il représente parfaitement la synthèse entre folklore et modernité. Le majeur hongrois incarne l'âme même de la musique tzigane avec son mélange paradoxal d'exubérance et de tragédie, défiant les catégories émotionnelles simplistes de la tradition occidentale.",
      culture: "Tzigane & Hongroise",
    },
    {
      name: "enigmatic",
      aliases: ["enigmatic scale"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3M", "4A", "5A", "6M", "7M"],
      alt: ["b2", "#4", "#5"],
      triad: "augmented",
      seventh: "maj7#5",
      description: "La gamme énigmatique, créée par Giuseppe Verdi comme défi théorique, incarne la recherche de nouvelles frontières expressives dans la musique occidentale tardive. Elle évoque mystère, tension irrésolue et cette qualité éthérée qui semble transcender les limites de la tonalité traditionnelle. Sa structure inhabituelle, accumulant les altérations ascendantes après une seconde mineure initiale, crée cette tension harmonique qui défie l'analyse conventionnelle. Utilisée par des compositeurs comme Scriabin et certains musiciens de jazz expérimental, elle représente l'exploration des limites de la tonalité. La gamme énigmatique, comme son nom l'indique, incarne parfaitement cette période charnière où la musique occidentale questionnait ses propres fondements, annonçant les révolutions atonales du 20e siècle.",
      culture: "Post-romantique européen",
    },
    {
      name: "neapolitan major",
      aliases: ["neapolitan"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3m", "4P", "5P", "6M", "7M"],
      alt: ["b2", "b3"],
      triad: "minor",
      seventh: "minMaj7",
      description: "La gamme napolitaine majeure, avec sa seconde mineure caractéristique, évoque l'élégance mélancolique de l'Italie baroque. Elle combine la sophistication harmonique du classicisme européen avec une touche d'exotisme méditerranéen, créant cette tension expressive subtile. Utilisée abondamment dans la musique baroque et classique, notamment par Scarlatti et Mozart, elle colore les compositions d'une gravité noble et distinguée. Sa seconde mineure initiale contraste avec la sixte et septième majeures pour créer ce mélange unique de tension et de résolution. La gamme napolitaine majeure illustre parfaitement l'influence des modes folkloriques méditerranéens sur la musique savante européenne, représentant ce dialogue constant entre tradition populaire et sophistication académique qui a enrichi l'histoire musicale occidentale.",
      culture: "Baroque italien",
    },
    {
      name: "neapolitan minor",
      aliases: ["neapolitan min"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3m", "4P", "5P", "6m", "7M"],
      alt: ["b2", "b3", "b6"],
      triad: "minor",
      seventh: "minMaj7",
      description: "La gamme napolitaine mineure, fusionnant la seconde mineure caractéristique avec la structure du mineur harmonique, crée une intensité dramatique particulièrement adaptée à l'expression de la passion et du pathos. Elle évoque la noblesse tragique, la mélancolie distinguée et cette tension dramatique qui caractérise l'opéra italien romantique. Utilisée par des compositeurs comme Bellini et Donizetti, elle colore les compositions d'une gravité émotionnelle intense sans tomber dans le mélodrame. Sa combinaison de seconde mineure et septième majeure crée cette tension harmonique sophistiquée qui distingue la tradition classique européenne. La gamme napolitaine mineure représente parfaitement l'expressivité émotionnelle raffinée de la musique romantique, où chaque nuance harmonique traduit une subtilité émotionnelle.",
      culture: "Romantique italien",
    },
  
    // GAMMES DE JAZZ ET CONTEMPORAINES
    {
      name: "bebop major",
      aliases: ["bebop", "bebop dominant"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3M", "4P", "5P", "6M", "7m", "7M"],
      alt: ["b7", "7"],
      triad: "major",
      seventh: "7",
      description: "La gamme bebop majeure, avec sa note chromatique de passage entre la septième mineure et l'octave, incarne la sophistication mélodique du jazz moderne. Elle facilite le phrasé caractéristique du bebop où les notes importantes tombent sur les temps forts tout en maintenant le flux continu de croches. Développée par des pionniers comme Charlie Parker et Dizzy Gillespie, elle représente l'évolution du langage jazz vers une plus grande complexité harmonique et mélodique. Sa structure à huit notes permet ces lignes virtuoses qui définissent l'esthétique bebop. La gamme bebop majeure illustre parfaitement comment les musiciens de jazz ont transformé les contraintes de la musique occidentale en opportunités créatives, développant un langage musical novateur tout en respectant les fondements harmoniques traditionnels.",
      culture: "Bebop américain",
    },
    {
      name: "bebop minor",
      aliases: ["bebop dorian"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "4P", "5P", "6M", "7m", "7M"],
      alt: ["b3", "7"],
      triad: "minor",
      seventh: "min7",
      description: "La gamme bebop mineure, fusionnant la structure dorienne avec une note chromatique de passage entre la septième mineure et l'octave, représente l'adaptation de l'esthétique bebop au contexte mineur. Elle permet ces lignes mélodiques fluides où les notes importantes tombent naturellement sur les temps forts. Utilisée par des musiciens comme Thelonious Monk et Bud Powell, elle enrichit l'improvisation jazz d'une sophistication mélodique sans sacrifier la profondeur émotionnelle du mode mineur. Sa structure à huit notes crée ce flux constant de croches caractéristique du style bebop. La gamme bebop mineure illustre parfaitement l'équilibre entre innovation technique et expressivité émotionnelle qui définit le jazz moderne, offrant aux improvisateurs un outil permettant virtuosité et profondeur.",
      culture: "Bebop américain",
    },
    {
      name: "bebop dominant",
      aliases: ["bebop mixolydian"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3M", "4P", "5P", "6M", "7m", "7M"],
      alt: ["b7", "7"],
      triad: "major",
      seventh: "7",
      description: "La gamme bebop dominante, enrichissant le mode mixolydien d'une note chromatique de passage, représente l'outil fondamental de l'improvisation sur accords de septième. Elle permet ces lignes fluides et virtuoses où les notes de l'accord tombent naturellement sur les temps forts lorsqu'on joue en croches régulières. Développée par les pionniers du bebop comme Charlie Parker, elle constitue le vocabulaire essentiel du jazz moderne. Sa structure à huit notes crée ce flux mélodique continu caractéristique du phrasé bebop. La gamme bebop dominante illustre parfaitement l'ingéniosité des musiciens de jazz qui ont su créer un langage mélodique sophistiqué à partir des contraintes harmoniques, transformant la note chromatique de passage en élément expressif distinctif.",
      culture: "Bebop américain",
    },
    {
      name: "lydian dominant pentatonic",
      aliases: ["dominant pentatonic"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "3M", "4A", "5P", "7m"],
      alt: ["#4", "b7"],
      triad: "lydian",
      seventh: "7#11",
      description: "La gamme pentatonique lydienne dominante combine la brillance éthérée de la quarte augmentée à la tension bluesy de la septième mineure dans une structure pentatonique accessible. Elle évoque à la fois sophistication harmonique et expressivité directe, créant un pont parfait entre jazz modal et tradition blues. Utilisée par des guitaristes comme John Scofield et Kurt Rosenwinkel, elle offre une alternative coloriée aux pentatoniques traditionnelles pour l'improvisation sur accords dominants altérés. Sa structure pentatonique minimaliste avec deux notes caractéristiques crée cette sonorité immédiatement reconnaissable. La pentatonique lydienne dominante représente parfaitement l'évolution du langage improvisé moderne, fusionnant accessibilité du blues et sophistication harmonique du jazz contemporain en un vocabulaire expressif unique.",
      culture: "Jazz fusion",
    },
  
    // GAMMES SUPPLÉMENTAIRES
    {
      name: "leading whole tone",
      aliases: ["lydian dominant b2"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3M", "4A", "5P", "6M", "7m"],
      alt: ["b2", "#4", "b7"],
      triad: "lydian",
      seventh: "7#11",
      description: "La gamme 'leading whole tone', fusion entre la seconde mineure phrygienne et la structure lydienne dominante, crée une tension harmonique sophistiquée particulièrement adaptée aux contextes modaux contemporains. Elle associe l'exotisme oriental de la seconde mineure à la brillance moderne de la quarte augmentée et la tension bluesy de la septième mineure. Utilisée dans le jazz contemporain et certaines musiques de film, elle colore les compositions d'une tension dramatique unique. Sa combinaison paradoxale d'intervalles crée cette qualité à la fois terrienne et éthérée, entre ancrage et transcendance. La 'leading whole tone' représente parfaitement l'évolution du langage modal moderne, où les frontières entre traditions orientales et occidentales s'effacent au profit d'une palette expressive globale.",
      culture: "Jazz contemporain",
    },
    {
      name: "six tone symmetrical",
      aliases: ["hexatonic", "augmented scale"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "3m", "3M", "5P", "5A", "7M"],
      alt: ["b3", "#5"],
      triad: "augmented",
      seventh: "maj7#5",
      description: "La gamme hexatonique symétrique, alternant systématiquement demi-tons et tons entiers plus demi, crée une structure parfaitement régulière qui défie la hiérarchie tonale traditionnelle. Elle évoque mystère, instabilité et cette qualité cyclique où la tension semble perpétuellement se renouveler. Utilisée par des compositeurs comme Bartók, Debussy et des jazzmen comme John Coltrane dans sa période expérimentale, elle offre de riches possibilités pour l'exploration harmonique contemporaine. Sa structure symétrique génère ces possibilités d'accords augmentés qui se déplacent par tierces majeures. L'hexatonique symétrique représente l'une des premières explorations systématiques des organisations sonores non-occidentales dans la musique européenne, annonçant les développements ultérieurs de la musique du 20e siècle.",
      culture: "Contemporain & Expérimental",
    },
    {
      name: "pelog",
      aliases: ["indonesian pelog"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3m", "5P", "6m"],
      alt: ["b2", "b3", "b6"],
      triad: "minor",
      seventh: "min7",
      description: "Le pélog, approximation occidentale d'un système d'accord indonésien, évoque immédiatement l'exotisme mystique des musiques de gamelan balinais et javanais. Sa structure pentatonique particulière, avec intervalles inégaux qui ne correspondent pas exactement au tempérament occidental, crée cette sonorité immédiatement reconnaissable et dépaysante. Centrale dans les traditions musicales indonésiennes, cette gamme a inspiré des compositeurs comme Debussy et Messiaen, fascinés par ses qualités timbrales uniques. Sa nature non-tempérée dans sa forme authentique rappelle les limites de notre notation occidentale face à la diversité des systèmes musicaux mondiaux. Le pélog illustre parfaitement comment les différentes cultures ont développé des approches radicalement différentes de l'organisation sonore, chacune reflétant une vision unique du monde et de l'expression artistique.",
      culture: "Indonésienne",
    },
    {
      name: "prometheus neopolitan",
      aliases: ["scriabin"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3M", "4A", "6M", "7m"],
      alt: ["b2", "#4", "b7"],
      triad: "lydian",
      seventh: "7#11",
      description: "La gamme prométhéenne napolitaine, développée par Scriabine, fusionne la seconde mineure napolitaine avec la tension mystique de la quarte augmentée et la septième mineure dominante. Elle évoque transcendance, extase mystique et cette qualité visionnaire qui caractérise les compositions tardives du compositeur russe. Centrale dans le développement de son système harmonique personnel, elle représente sa quête d'une musique capable d'élever la conscience humaine. Sa combinaison unique d'intervalles génère ces harmonies caractéristiques de sa période mystique, notamment l'accord 'mystique' ou 'prométhéen'. La gamme prométhéenne napolitaine incarne parfaitement la recherche d'une nouvelle spiritualité à travers l'art qui caractérisait le tournant du 20e siècle, où la musique était conçue comme véhicule d'élévation spirituelle et de transformation de la conscience.",
      culture: "Mystique russe",
    },
    {
      name: "super locrian",
      aliases: ["altered dominant"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3m", "4d", "5d", "6m", "7m"],
      alt: ["b2", "b3", "b4", "b5", "b6", "b7"],
      triad: "diminished",
      seventh: "7alt",
      description: "Le mode super locrien, avec ses multiples altérations descendantes, représente l'apogée de la tension harmonique dans le langage jazz. Il évoque instabilité maximale, urgence de résolution et cette qualité dramatique particulièrement adaptée aux dominantes altérées. Essentiel dans le vocabulaire du jazz moderne et contemporain, il offre un maximum de tensions disponibles pour l'improvisation sur les accords dominants altérés. Sa structure particulière, où presque chaque degré est altéré vers le bas, génère cette instabilité extrême qui valorise sa résolution finale. Le super locrien incarne l'évolution ultime du langage harmonique jazz, poussant la sophistication harmonique à ses limites tout en maintenant une fonction tonale claire dans les progressions II-V-I avancées.",
      culture: "Jazz contemporain",
    },
    {
      name: "algerian",
      aliases: ["north african"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "4A", "5P", "6m", "7M"],
      alt: ["b3", "#4", "b6"],
      triad: "minor",
      seventh: "minMaj7",
      description: "La gamme algérienne, synthèse d'influences berbères, arabes et andalouses, capture l'essence même des traditions musicales nord-africaines. Elle évoque instantanément les vastes paysages désertiques, la chaleur méditerranéenne et cette mélancolie particulière teintée de fierté qui caractérise l'expression musicale maghrébine. Sa structure unique, combinant éléments mineurs et altérations orientales, crée cette tension expressive intense si caractéristique. Fondamentale dans les musiques traditionnelles et populaires d'Afrique du Nord, elle a inspiré de nombreux compositeurs occidentaux fascinés par ses qualités exotiques. La gamme algérienne représente parfaitement le carrefour culturel qu'est le Maghreb, où influences africaines, méditerranéennes et moyen-orientales se fondent en une expression artistique unique et reconnaissable.",
      culture: "Nord-africaine",
    },
  
    // MODES ADDITIONNELS
    {
      name: "lydian flat 7",
      aliases: ["mixolydian #4", "overtone"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3M", "4A", "5P", "6M", "7m"],
      alt: ["#4", "b7"],
      triad: "lydian",
      seventh: "7#11",
      description: "Le mode lydien bémol 7, fusionnant brillance lydienne et tension mixolydienne, incarne parfaitement l'équilibre entre sophistication harmonique et accessibilité bluesy. Il évoque à la fois élévation spirituelle et ancrage terrestre, créant ce pont unique entre transcendance et expression directe. Fondamental dans le jazz modal et la fusion, notamment dans les compositions d'artistes comme Pat Metheny ou Wayne Shorter, il colore l'improvisation d'une tension expressive unique. Sa structure, dérivée de la série des harmoniques naturelles, explique son autre nom de 'gamme acoustique'. Le lydien bémol 7 représente l'évolution naturelle du langage modal jazz, offrant aux improvisateurs une palette expressive qui transcende les limitations du système majeur/mineur tout en maintenant une cohérence harmonique immédiatement perceptible.",
      culture: "Jazz modal",
    },
    {
      name: "mixolydian b9 b13",
      aliases: ["phrygian dominant"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3M", "4P", "5P", "6m", "7m"],
      alt: ["b2", "b6", "b7"],
      triad: "major",
      seventh: "7",
      description: "Le mode mixolydien bémol 9 bémol 13, équivalent au phrygien dominant, fusionne l'énergie du mixolydien avec la tension orientale du phrygien. Il évoque immédiatement passion méditerranéenne, chaleur espagnole et cette intensité expressive si caractéristique du flamenco et des musiques moyen-orientales. Sa seconde mineure distinctive crée cette tension initiale immédiate qui capte instantanément l'attention de l'auditeur. Fondamental dans le flamenco, la musique andalouse et diverses traditions méditerranéennes et moyen-orientales, il a inspiré d'innombrables compositeurs occidentaux fascinés par son exotisme. Le mixolydien bémol 9 bémol 13 incarne parfaitement la fusion entre cultures musicales européennes et arabes qui s'est opérée autour de la Méditerranée, créant cette expression artistique unique qui transcende les frontières géographiques et culturelles.",
      culture: "Méditerranéenne & Flamenco",
    },
    {
      name: "locrian #6",
      aliases: ["aeolian b5"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3m", "4P", "5d", "6M", "7m"],
      alt: ["b2", "b3", "b5", "b7"],
      triad: "diminished",
      seventh: "min7b5",
      description: "Le mode locrien dièse 6, variante moins sévère du locrien, adoucit légèrement sa tension extrême grâce à sa sixte majeure. Il évoque désespoir teinté d'espérance, tension qui entrevoit une possible résolution, créant un équilibre fascinant entre ombre et lumière. Utilisé dans le jazz contemporain, notamment sur les accords demi-diminués des progressions II-V-I mineures, il offre une palette expressive riche pour l'improvisation avancée. Sa sixte majeure apporte cette lueur d'espoir dans la noirceur caractéristique du locrien standard. Le locrien dièse 6 représente parfaitement l'équilibre subtil entre tension et résolution qui caractérise les langages harmoniques sophistiqués, offrant aux compositeurs et improvisateurs un outil expressif capable de nuances émotionnelles complexes et paradoxales.",
      culture: "Jazz contemporain",
    },
    {
      name: "locrian major",
      aliases: ["ionian b2 b3"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3m", "4P", "5P", "6M", "7M"],
      alt: ["b2", "b3"],
      triad: "minor",
      seventh: "minMaj7",
      description: "Le mode locrien majeur, fusion paradoxale d'éléments locrien et ionien, crée une tension harmonique unique avec sa combinaison de seconde mineure et septième majeure. Il évoque une dualité expressive entre ombre et lumière, tension et résolution, créant ce contraste dynamique particulièrement adapté aux contextes harmoniques contemporains. Utilisé dans le jazz moderne et certaines musiques de film, il colore les compositions d'une ambiguïté tonale sophistiquée. Sa structure intervalique inhabituelle génère ces possibilités harmoniques qui transcendent les catégories traditionnelles majeur/mineur. Le locrien majeur illustre parfaitement l'évolution du langage modal moderne vers des expressions hybrides qui reflètent la complexité émotionnelle contemporaine, où les frontières entre catégories traditionnelles s'estompent au profit d'une palette expressive plus nuancée.",
      culture: "Contemporain",
    },
    {
      name: "romanian minor",
      aliases: ["ukrainian dorian"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "4A", "5P", "6m", "7m"],
      alt: ["b3", "#4", "b6", "b7"],
      triad: "minor",
      seventh: "min7",
      description: "Le mode mineur roumain, avec sa quarte augmentée caractéristique, capture l'essence même des traditions musicales d'Europe de l'Est. Il évoque les vastes plaines ukrainiennes, les danses folkloriques endiablées et cette mélancolie particulière teintée de fatalisme qui caractérise l'âme slave. Sa structure unique, fusionnant éléments du mineur dorien et altérations orientales, crée cette tension expressive si caractéristique. Fondamental dans les musiques traditionnelles roumaines, ukrainiennes et des Balkans, il a inspiré des compositeurs comme Bartók et Enesco dans leurs recherches ethnomusicologiques. Le mineur roumain illustre parfaitement le carrefour culturel qu'est l'Europe de l'Est, où influences occidentales, orientales et balkaniques se fondent en une expression artistique unique et immédiatement reconnaissable.",
      culture: "Roumaine & Est-européenne",
    },
    {
      name: "hindu",
      aliases: ["indian"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3M", "4P", "5P", "6m", "7m"],
      alt: ["b6", "b7"],
      triad: "major",
      seventh: "7",
      description: "Le mode hindou, adaptation occidentale du raga Kafi de la musique indienne classique, fusionne la brillance majeure avec une tension mélancolique créée par ses sixte et septième mineures. Il évoque la spiritualité indienne, la richesse expressive du sous-continent et cette dualité entre joie et détachement qui caractérise la philosophie hindoue. Sa structure, similaire au mode mixolydien avec une sixte mineure, crée cette tension expressive particulière, à la fois familière et exotique. Bien qu'il ne capture qu'imparfaitement la complexité microtonale des ragas indiens authentiques, il offre une approximation accessible de leurs qualités expressives. Le mode hindou illustre les tentatives occidentales d'intégrer les traditions musicales indiennes dans un cadre théorique familier, créant un pont culturel qui a inspiré d'innombrables compositeurs et musiciens.",
      culture: "Indienne (approximation)",
    },
    {
      name: "spanish",
      aliases: ["spanish 8 tone"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2m", "3M", "4P", "5P", "6m", "7m", "7M"],
      alt: ["b2", "b6", "b7", "7"],
      triad: "major",
      seventh: "7",
      description: "La gamme espagnole, fusion d'influences andalouses, mauresques et tziganes, capture l'essence même du flamenco et de la musique ibérique traditionnelle. Elle évoque immédiatement passion, intensité dramatique et cette dualité entre fierté et mélancolie si caractéristique de l'expression espagnole. Sa structure unique, combinant phrygien dominant et note chromatique de passage, crée cette tension expressive intense qui semble traduire l'histoire tumultueuse de la péninsule ibérique. Fondamentale dans le flamenco et la musique classique espagnole de compositeurs comme Albéniz et de Falla, elle incarne l'identité musicale espagnole la plus reconnaissable. La gamme espagnole représente parfaitement la fusion des influences musulmanes, juives, romanes et tziganes qui ont façonné la riche culture musicale de l'Espagne à travers les siècles.",
      culture: "Espagnole & Flamenco",
    },
    {
      name: "major blues",
      aliases: ["blues major scale"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3m", "3M", "5P", "6M"],
      alt: ["b3", "3"],
      triad: "major",
      seventh: "6",
      description: "La gamme blues majeure, fusion des pentatoniques majeure et mineure, capture l'essence même de l'expressivité blues dans un contexte plus lumineux. Elle évoque cette dualité caractéristique entre joie et mélancolie, optimisme et réalisme, qui définit l'âme du blues. Sa blue note (tierce mineure dans un contexte majeur) crée cette tension expressive unique qui permet ces glissements et inflexions si typiques de la guitare et de la voix blues. Utilisée par d'innombrables guitaristes et pianistes dans le blues, le rock et la country, elle représente le vocabulaire essentiel de l'improvisation blues. La blues majeure illustre parfaitement comment la tradition musicale afro-américaine a transformé la tierce flottante (entre majeure et mineure) en élément expressif fondamental, créant un langage musical qui transcende les catégories occidentales traditionnelles.",
      culture: "Blues américain",
    },
    {
      name: "minor hex",
      aliases: ["minor hexatonic"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "3m", "4P", "5P", "6M", "7M"],
      alt: ["b3"],
      triad: "minor",
      seventh: "minMaj7",
      description: "La gamme hexatonique mineure, avec sa combinaison unique de tierce mineure et septième majeure, crée une tension harmonique sophistiquée particulièrement adaptée aux contextes jazz contemporains. Elle évoque mélancolie sophistiquée, introspection nuancée et cette tension subtile qui cherche résolution sans tomber dans le désespoir. Utilisée par des pianistes comme Bill Evans et des guitaristes comme Kurt Rosenwinkel, elle colore l'improvisation d'une expressivité raffinée et moderne. Sa structure hexatonique sans seconde ni sixte génère ces possibilités harmoniques qui transcendent les catégories traditionnelles majeur/mineur. L'hexatonique mineure illustre parfaitement l'évolution du langage improvisatoire moderne vers des expressions plus nuancées et sophistiquées, reflétant la complexité émotionnelle contemporaine à travers un vocabulaire musical en constante évolution.",
      culture: "Jazz contemporain",
    },
    {
      name: "major hex",
      aliases: ["major hexatonic"],
      modeNum: 0,
      mode: 0,
      intervals: ["1P", "2M", "3M", "5P", "6M", "7M"],
      alt: [],
      triad: "major",
      seventh: "maj7",
      description: "La gamme hexatonique majeure, avec son absence caractéristique de quarte et de septième mineure, crée une sonorité aérienne et ouverte particulièrement adaptée aux contextes harmoniques modernes. Elle évoque sérénité, espace et cette qualité flottante qui semble transcender les tensions harmoniques traditionnelles. Utilisée par des pianistes comme Kenny Barron et des guitaristes comme Pat Metheny, elle colore l'improvisation d'une luminosité expansive et contemplative. Sa structure hexatonique sans quarte ni septième mineure génère ces possibilités harmoniques qui évitent les tensions traditionnelles tout en maintenant une direction tonale claire. L'hexatonique majeure illustre parfaitement l'évolution du langage modal vers des expressions plus épurées et méditatives, où l'espace et la retenue deviennent aussi importants que les notes jouées.",
      culture: "Jazz moderne",
    }
  ];